var shuffleSequence = seq("intro", "info", "practice", sepWith("sep", shuffle(randomize("filler"), rshuffle("SC","DO"))), "outtro");

var ds = "RegionedSentence"
var qs = "Question"

var defaults = [
    "Separator", {
        transfer: 1500,
        normalMessage: "Please wait for the next sentence",
        errorMessage: "Wrong. Please wait for the next sentence" },
    "RegionedSentence", {
        mode: "self-paced reading" },
    "Question", {
        as: ["Yes","No"],
        randomOrder: false,
        hasCorrect: true }
];

var items = [
    ["sep", "Separator", {}],
    ["intro", "Message", {consentRequired: true, html: {include: "intro.html"}}],
    ["info", "Form", {html: { include: "info.html" }, } ],
    [["SC",1], ds, {s: "The talented photographer accepted the money could not be spent yet. "}, 
        qs, {q: "Could the money be spent? " , hasCorrect: "No", randomOrder: false}],
    [["DO",1], ds, {s: "The talented photographer accepted the money with much reluctance."}, 
        qs, {q: "Was the photographer eager to take the money? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[2,1]], ds, {s: "The newspaper editor advocated the truth publicly and with great zeal."}, 
        qs, {q: "Did the editor want to hide the truth? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[2,1]], ds, {s: "The newspaper editor advocated the truth needed to be made public."}, 
        qs, {q: "Did the editor want to hide the truth? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[3,1]], ds, {s: "The divorce lawyer argued the issue was irrelevant to the case."}, 
        qs, {q: "Was the relevance of the issue unquestioned? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[3,1]], ds, {s: "The divorce lawyer argued the issue with her colleague across the state."}, 
        qs, {q: "Did the lawyer specialize in auto accidents? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[4,1]], ds, {s: "The job applicant believed the interviewer when she discussed things with her."}, 
        qs, {q: "Was the applicant very suspicious of the interviewer? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[4,1]], ds, {s: "The job applicant believed the interviewer had been dishonest with her."}, 
        qs, {q: "Was the applicant suspicious of the interviewer? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[5,1]], ds, {s: "The weary traveler claimed the luggage had been stolen in Rome."}, 
        qs, {q: "Was the traveler tired? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[5,1]], ds, {s: "The weary traveler claimed the luggage at the counter in Prague."}, 
        qs, {q: "Did the traveler get her luggage in Paris? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[6,1]], ds, {s: "The account executive concluded the speech with a joke about style."}, 
        qs, {q: "Did the speech end on a serious note? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[6,1]], ds, {s: "The account executive concluded the speech had not gone very well."}, 
        qs, {q: "Was the speech a huge success? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[7,1]], ds, {s: "The bank guard confessed the robbery had been his idea."}, 
        qs, {q: "Was the bank guard involved in the robbery? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[7,1]], ds, {s: "The bank guard confessed the robbery after a sleepless night."}, 
        qs, {q: "Was the bank robber guilty? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[8,1]], ds, {s: "The CIA director confirmed the rumor should have been stopped sooner."}, 
        qs, {q: "Had the rumor been stopped? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[8,1]], ds, {s: "The CIA director confirmed the rumor once it had spread widely."}, 
        qs, {q: "Did the CIA director eventually own up to the truth? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[9,1]], ds, {s: "The experienced judge decided the appeal on the merit of the case."}, 
        qs, {q: "Was the judge fair? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[9,1]], ds, {s: "The experienced judge decided the appeal should be started right away."}, 
        qs, {q: "Did the judge want to delay the appeal? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[10,1]], ds, {s: "The angry father emphasized the problems faced by those who lived far away."}, 
        qs, {q: "Did the father focus on the good fortune of others? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[10,1]], ds, {s: "The angry father emphasized the problems were continuing to get worse."}, 
        qs, {q: "Was the father pleased? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[11,1]], ds, {s: "The primary suspect established the alibi had been a total lie."}, 
        qs, {q: "Was the alibi false? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[11,1]], ds, {s: "The primary suspect established the alibi with the help of an old spy."}, 
        qs, {q: "Did the suspect have an accomplice? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[12,1]], ds, {s: "The shrewd salesman figured the prices would be going up soon."}, 
        qs, {q: "Was it possible the prices would change? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[12,1]], ds, {s: "The shrewd salesman figured the prices for the recent book sale."}, 
        qs, {q: "Was the salesman worried about prices for a recent car sale? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[13,1]], ds, {s: "The gossipy neighbor heard the story of how the five others had left."}, 
        qs, {q: "Was the story about four people? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[13,1]], ds, {s: "The gossipy neighbor heard the story had never actually been true."}, 
        qs, {q: "Was the story to be trusted? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[14,1]], ds, {s: "The confident engineer maintained the machinery would be hard to destroy."}, 
        qs, {q: "Was the engineer hesitant? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[14,1]], ds, {s: "The confident engineer maintained the machinery of the whole upper deck."}, 
        qs, {q: "Was the engineer responsible for the upper deck? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[15,1]], ds, {s: "The journal editor printed the article with the footnotes at the end."}, 
        qs, {q: "Did the article have footnotes? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[15,1]], ds, {s: "The journal editor printed the article had been slanderous to him."}, 
        qs, {q: "Did the editor like the column? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[16,1]], ds, {s: "The novice plumber realized the mistake before calling the owner."}, 
        qs, {q: "Did the plumber catch his error? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[16,1]], ds, {s: "The novice plumber realized the mistake would cost someone some money."}, 
        qs, {q: "Would the mistake come at a cost? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[17,1]], ds, {s: "The film director suggested the scene should be filmed at night."}, 
        qs, {q: "Did the director want to shoot the scene during the day? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[17,1]], ds, {s: "The film director sugested the scene between Bonnie and Clyde."}, 
        qs, {q: "Was the scene the producer's idea? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[18,1]], ds, {s: "The high school principal suspected the teenager who always arrived to school late."}, 
        qs, {q: "Was the tardy student a suspect? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[18,1]], ds, {s: "The high school principal suspected the teenager sometimes cheated in class."}, 
        qs, {q: "Was the high-school principal distrustful of the student? " , hasCorrect: "Yes", randomOrder: false}],
    [["SC",[19,1]], ds, {s: "The frustrated tourists understood the message would mean they couldn't go."}, 
        qs, {q: "Did the message mean the tourists could go? " , hasCorrect: "No", randomOrder: false}],
    [["DO",[19,1]], ds, {s: "The frustrated tourists understood the message when it had been explained."}, 
        qs, {q: "Did the tourists eventually get the message? " , hasCorrect: "Yes", randomOrder: false}],
    [["DO",[20,1]], ds, {s: "The art critic wrote the interview with little regard for readers."}, 
        qs, {q: "Did the critic carefully consider her readers when writing the interview? " , hasCorrect: "No", randomOrder: false}],
    [["SC",[20,1]], ds, {s: "The art critic wrote the interview had been a complete disaster."}, 
        qs, {q: "Was the art critic displeased with the interview? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The new student caught everyone's attention when he came into the room."}, 
        qs, {q: "Did everyone ignore the student when he came into the room? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "Each of the cab drivers had their own favorite route to get to the airport."}, 
        qs, {q: "Was there more than one way to get to the airport? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The nurses that worked in the intensive care unit all wanted to have more holidays off."}, 
        qs, {q: "Did the nurses want more time off? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The carpenter ended up with a sunburn."}, 
        qs, {q: "Was the carpenter able to avoid getting sunburn? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The valuable lamp was broken by the mischievous boy. "}, 
        qs, {q: "Was the vase valuable? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The record store sold albums primarily to college students in the neighborhood."}, 
        qs, {q: "Did college kids shop at the record store? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The eccentric professor always inspired his students to think critically about their work."}, 
        qs, {q: "Did the professor encourage laziness in his students? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The police put a man in jail for robbing a liquor store."}, 
        qs, {q: "Was the man incarcerated? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The shoe salesman looked impatiently out the window while waiting for customers."}, 
        qs, {q: "Was the salesman eager for business? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The prisoners were unable to cross the field without being seen."}, 
        qs, {q: "Were the prisoners able to cross the field unseen? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The former drug addict's memoirs were met with critical acclaim."}, 
        qs, {q: "Were the memoirs despised by critics? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The girls on the basketball team trained and practiced all summer."}, 
        qs, {q: "Were the girls lazy all summer? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The power plant deserved more attention from the candidates during the election."}, 
        qs, {q: "Did the plant receive adequate attention in the election? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The library was open to all members of the community since it was supported by tax dollars."}, 
        qs, {q: "Was the library funded by taxpayers? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The guest speaker nervously cleared his throat before addressing the small audience."}, 
        qs, {q: "Was the speaker completely calm before speaking? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The children in the park could be heard three blocks away."}, 
        qs, {q: "Were the children being quiet? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The quilts were sold by the side of the road for ten dollars."}, 
        qs, {q: "Did the quilts cost twenty dollars? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The flags in the gym represented all the different countries participating in the tournament."}, 
        qs, {q: "Were the flags chosen at random? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The map's labels for the former Soviet states were out of date."}, 
        qs, {q: "Were the map's labels up to date? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The physics professor at the university was finally going to retire."}, 
        qs, {q: "Was the professor just starting his career? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The school librarian selected books that the library patrons would enjoy."}, 
        qs, {q: "Did the English teacher pick out the books? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The engineers at the plant wore helmets when they went near the machines."}, 
        qs, {q: "Did the engineers take any safety measures? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The leader of the crime ring was always suspicious of his business partners."}, 
        qs, {q: "Was the crime leader suspicious? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "Parliament members debated trivial financial issues while the protestors grew more restless."}, 
        qs, {q: "Did parliament members discuss important policy issues? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The bulldozers cleared rubble from the demolished building."}, 
        qs, {q: "Did the bulldozers clear away debris from the building? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The school principal worked constantly all summer dealing with paperwork."}, 
        qs, {q: "Was the principal busy? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "Bikes were not permitted on the town's sidewalks."}, 
        qs, {q: "Did people bike on the sidewalks? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The drill sergeant forced the men to do hundreds of push-ups and sit-ups."}, 
        qs, {q: "Did the men volunteer to do sit-ups and push-ups? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The businessmen were made sick by the rancid poultry."}, 
        qs, {q: "Did the businessmen eat poultry? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The laptops were too expensive for most of the students."}, 
        qs, {q: "Were the laptops affordable for the students? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "Many of the city cops refuse to work in the rough parts of town."}, 
        qs, {q: "Were there parts of town where cops wouldn't work? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "All the parents at the meeting strongly disagreed with the new policy."}, 
        qs, {q: "Did the parents like the new policy? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The new experiment was the source of a great deal of excitement in the lab."}, 
        qs, {q: "Was everyone bored by the experiment? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The store manager carefully cleaned both the interior and exterior of the store."}, 
        qs, {q: "Did the manager care about the appearance of the store? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "All the undergraduates in the class had trouble keeping up."}, 
        qs, {q: "Was the class easy for the undergrads? " , hasCorrect: "No", randomOrder: false}],
    ["filler", ds, {s: "The espresso machine was broken for months before finally being fixed."}, 
        qs, {q: "Was the espresso machine fixed? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The truck veered off of the road after its brakes failed."}, 
        qs, {q: "Did the truck's brakes malfunction? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The band set up their equipment before the concert."}, 
        qs, {q: "Did the band set up their equipment? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "The lifeguard watched over his part of the beach all day."}, 
        qs, {q: "Did the lifeguard have a designated portion of the beach to watch? " , hasCorrect: "Yes", randomOrder: false}],
    ["filler", ds, {s: "Warm milk always soothed the infants in the nursery."}, 
        qs, {q: "Did the nursery use warm milk to calm the infants? " , hasCorrect: "Yes", randomOrder: false}],
    ["outtro", "Message", {consentRequired: false, html: {include: "contacts.html"}}] 
];

